In [9]:
import qutip as qu
import numpy as np
import matplotlib.pyplot

In [10]:
def qu_L(L):
    return qu.Qobj(np.array(L), dims=[[[2], [2]], [[2], [2]]], shape=(4, 4), type="super")

In [63]:
N = 2 #dimension of Hilbert Space
G = np.array([qu.identity(N), qu.sigmax(), qu.sigmay(), qu.sigmaz()])/np.sqrt(N)
G


array([[[ 0.70710678+0.j        ,  0.        +0.j        ],
        [ 0.        +0.j        ,  0.70710678+0.j        ]],

       [[ 0.        +0.j        ,  0.70710678+0.j        ],
        [ 0.70710678+0.j        ,  0.        +0.j        ]],

       [[ 0.        +0.j        ,  0.        -0.70710678j],
        [ 0.        +0.70710678j,  0.        +0.j        ]],

       [[ 0.70710678+0.j        ,  0.        +0.j        ],
        [ 0.        +0.j        , -0.70710678+0.j        ]]])

In [12]:
xij_example = qu.rand_herm(N**2, seed = 9)
xij_example

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[-0.97925169+0.j          0.        +0.j         -0.42016706-0.39268663j
   0.        +0.j        ]
 [ 0.        +0.j         -0.56288265+0.j         -0.23599318+0.02113069j
  -0.71315046-0.47984894j]
 [-0.42016706+0.39268663j -0.23599318-0.02113069j -0.66644731+0.j
   0.57766648-0.47990421j]
 [ 0.        +0.j         -0.71315046+0.47984894j  0.57766648+0.47990421j
   0.14551963+0.j        ]]

In [13]:
H = np.array([[1, 0], [0, 0]])

In [14]:
ex_super = qu.rand_super(2, seed=7)

In [15]:
qu.to_choi(ex_super)

Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = (4, 4), type = super, isherm = True, superrep = choi
Qobj data =
[[ 0.66891681+0.j         -0.01799044+0.04207126j -0.00297182+0.04565978j
   0.40317088+0.19425579j]
 [-0.01799044-0.04207126j  0.33108319+0.j          0.00524264-0.00184916j
   0.00297182-0.04565978j]
 [-0.00297182-0.04565978j  0.00524264+0.00184916j  0.33108319+0.j
   0.01799044-0.04207126j]
 [ 0.40317088-0.19425579j  0.00297182+0.04565978j  0.01799044+0.04207126j
   0.66891681+0.j        ]]

In [16]:
qu.liouvillian(qu.Qobj(H))

Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = (4, 4), type = super, isherm = False
Qobj data =
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.-1.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]

In [17]:
# I want to go from super to choi with my notes, I need to expand in the |ij> < ij|
# Creation of ket ij

set_ket_ij = []
for i in range(2):
    for j in range(2):
        set_ket_ij.append(np.kron(qu.basis(2, i).full(), qu.basis(2, j).full()))


set_ket_ij = np.array(set_ket_ij)


set_ket_i = []
for i in range(2):
    set_ket_i.append(np.kron(qu.basis(2, i).full(), qu.basis(2, i).full()))

set_ket_i = np.array(set_ket_i)

In [18]:
ex_super

Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = (4, 4), type = super, isherm = False
Qobj data =
[[ 0.66891681+0.j         -0.00297182-0.04565978j -0.00297182+0.04565978j
   0.33108319+0.j        ]
 [-0.01799044-0.04207126j  0.40317088-0.19425579j  0.00524264-0.00184916j
   0.01799044+0.04207126j]
 [-0.01799044+0.04207126j  0.00524264+0.00184916j  0.40317088+0.19425579j
   0.01799044-0.04207126j]
 [ 0.33108319+0.j          0.00297182+0.04565978j  0.00297182-0.04565978j
   0.66891681+0.j        ]]

In [19]:
J = np.zeros([2, 2, 2, 2], dtype=np.complex64)
for i in range(2):
    for j in range(2):
        for k in range(2):
            for l in range(2):
                ket = np.kron(qu.basis(2, i).full(), qu.basis(2, j).full())
                bra = np.kron(qu.basis(2, k).full(), qu.basis(2, l).full())
                J[i, j, k, l] = np.conjugate(bra.T) @ ex_super.full() @ ket

In [20]:
J

array([[[[ 0.6689168 +0.j        , -0.01799044-0.04207126j],
         [-0.01799044+0.04207126j,  0.33108318+0.j        ]],

        [[-0.00297182-0.04565978j,  0.40317088-0.19425578j],
         [ 0.00524264+0.00184916j,  0.00297182+0.04565978j]]],


       [[[-0.00297182+0.04565978j,  0.00524264-0.00184916j],
         [ 0.40317088+0.19425578j,  0.00297182-0.04565978j]],

        [[ 0.33108318+0.j        ,  0.01799044+0.04207126j],
         [ 0.01799044-0.04207126j,  0.6689168 +0.j        ]]]],
      dtype=complex64)

In [21]:
J_ijij = np.transpose(J, axes=[0, 2, 1, 3])
# J_ijij = J

#if u want it in two dimensions, you need to expand it 

choi = 0
for i in range(2):
    for j in range(2):
        for k in range(2):
            for l in range(2):
                ket = np.kron(qu.basis(2, i).full(), qu.basis(2, j).full())
                bra = np.kron(qu.basis(2, k).full(), qu.basis(2, l).full())
                #  = np.conjugate(bra.T) @ ex_super.full() @ ket
                # print()
                choi = choi + bra@ket.T*J_ijij[i, j, k, l]


np.isclose(
    qu.to_choi(ex_super).full(),
    choi)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [25]:
def to_choi_from_super(superop):
    J = np.zeros([2, 2, 2, 2], dtype=np.complex64)
    for i in range(2):
        for j in range(2):
            for k in range(2):
                for l in range(2):
                    ket = np.kron(qu.basis(2, i).full(), qu.basis(2, j).full())
                    bra = np.kron(qu.basis(2, k).full(), qu.basis(2, l).full())
                    J[i, j, k, l] = np.conjugate(bra.T) @ superop @ ket

    J_ijij = np.transpose(J, axes=[0, 2, 1, 3])
    choi = 0
    for i in range(2):
        for j in range(2):
            for k in range(2):
                for l in range(2):
                    ket = np.kron(qu.basis(2, i).full(), qu.basis(2, j).full())
                    bra = np.kron(qu.basis(2, k).full(), qu.basis(2, l).full())
                    choi = choi + bra @ ket.T * J_ijij[i, j, k, l]

    return choi

In [62]:
qu.basis(2, 0).full()

array([[1.+0.j],
       [0.+0.j]])

In [28]:
to_choi_from_super(ex_super.full()), 

(array([[ 0.66891682+0.j        , -0.01799044+0.04207126j,
         -0.00297182+0.04565978j,  0.40317088+0.19425578j],
        [-0.01799044-0.04207126j,  0.33108318+0.j        ,
          0.00524264-0.00184916j,  0.00297182-0.04565978j],
        [-0.00297182-0.04565978j,  0.00524264+0.00184916j,
          0.33108318+0.j        ,  0.01799044-0.04207126j],
        [ 0.40317088-0.19425578j,  0.00297182+0.04565978j,
          0.01799044+0.04207126j,  0.66891682+0.j        ]]),)

In [113]:
np.transpose(ex_super.full().reshape([2, 2, 2, 2]), axes=[0, 3, 2, 1]).reshape([4, 4])

array([[ 0.66891681+0.j        , -0.01799044-0.04207126j,
        -0.00297182+0.04565978j,  0.00524264-0.00184916j],
       [-0.00297182-0.04565978j,  0.40317088-0.19425579j,
         0.33108319+0.j        ,  0.01799044+0.04207126j],
       [-0.01799044+0.04207126j,  0.33108319+0.j        ,
         0.40317088+0.19425579j,  0.00297182-0.04565978j],
       [ 0.00524264+0.00184916j,  0.00297182+0.04565978j,
         0.01799044-0.04207126j,  0.66891681+0.j        ]])

Convert to choi to xij

In [29]:
omega_ket = np.sum(np.array([np.kron(qu.basis(2, i), qu.basis(2, i)) for i in range(2)])/np.sqrt(2), axis=0)
omega_ket

array([[0.70710678+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.70710678+0.j]])

In [173]:
chimn = np.zeros([4, 4], dtype=np.complex64)

for i in range(4):
    for j in range(4):
        chimn[i, j] = (
            np.conjugate(omega_ket.T)
            @ np.kron(G[j], np.identity(2))
            @ choi
            @ np.kron(G[i], np.identity(2))
            @ omega_ket
        )

In [300]:
np.array([np.kron(qu.basis(2, i), qu.basis(2, i)) for i in range(2)])/ np.sqrt(2)

array([[[0.70710678+0.j],
        [0.        +0.j],
        [0.        +0.j],
        [0.        +0.j]],

       [[0.        +0.j],
        [0.        +0.j],
        [0.        +0.j],
        [0.70710678+0.j]]])

In [1]:
def to_chi_from_choi(choi):
    omega_ket = np.array(
        [np.kron(qu.basis(2, i), qu.basis(2, i)) for i in range(2)]
    ) / np.sqrt(2)

    chimn = np.zeros([4, 4], dtype=np.complex64)

    for i in range(4):
        for j in range(4):
            suma = 0
            for k in range(2):
                for l in range(2):
                    suma = suma + (
                        np.conjugate(omega_ket[k].T)
                        @ np.kron(
                            np.identity(2),
                            G[i]
                        )
                        @ choi
                        @ np.kron(np.identity(2), G[j])
                        @ omega_ket[l]
                    )
            chimn[i, j] = suma

    return chimn


def to_super_from_chi(xi):
    # return np.einsum("ij,ijkl -> kl ",  xi, G_ijkl)
    A = np.zeros([4, 4], dtype=np.complex64)
    for i in range(4):
        for j in range(4):
            A = A + xi[i][j] * np.kron(np.transpose(G[j]), G[i])
    return A

In [2]:
print(chimn.round(4))

NameError: name 'chimn' is not defined

In [52]:
xij_example

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[-0.97925169+0.j          0.        +0.j         -0.42016706-0.39268663j
   0.        +0.j        ]
 [ 0.        +0.j         -0.56288265+0.j         -0.23599318+0.02113069j
  -0.71315046-0.47984894j]
 [-0.42016706+0.39268663j -0.23599318-0.02113069j -0.66644731+0.j
   0.57766648-0.47990421j]
 [ 0.        +0.j         -0.71315046+0.47984894j  0.57766648+0.47990421j
   0.14551963+0.j        ]]

In [87]:
# xij_example = xij_example

# we go from xi to superop

superop = to_super_from_chi(xij_example.full())

# from superop we go to choi

choi_example = to_choi_from_super(superop)

#from choi to xi

xij_again = to_chi_from_choi(choi_example)*N


In [88]:
print(superop.round(3))

[[-0.417+0.j    -0.313+0.161j -0.313-0.161j -0.594+0.j   ]
 [-0.4  +0.319j -0.562+0.j     0.052-0.236j -0.08 -0.259j]
 [-0.4  -0.319j  0.052+0.236j -0.562+0.j    -0.08 +0.259j]
 [-0.636+0.j     0.793+0.739j  0.793-0.739j -0.417+0.j   ]]


In [89]:
print(xij_example.full().round(3))

[[-0.979+0.j     0.   +0.j    -0.42 -0.393j  0.   +0.j   ]
 [ 0.   +0.j    -0.563+0.j    -0.236+0.021j -0.713-0.48j ]
 [-0.42 +0.393j -0.236-0.021j -0.666+0.j     0.578-0.48j ]
 [ 0.   +0.j    -0.713+0.48j   0.578+0.48j   0.146+0.j   ]]


In [90]:
np.isclose(xij_example, xij_again)


array([[ True,  True, False,  True],
       [ True,  True, False,  True],
       [False, False,  True, False],
       [ True,  True, False,  True]])

In [92]:
print(xij_example.full().round(4))

[[-0.9793+0.j      0.    +0.j     -0.4202-0.3927j  0.    +0.j    ]
 [ 0.    +0.j     -0.5629+0.j     -0.236 +0.0211j -0.7132-0.4798j]
 [-0.4202+0.3927j -0.236 -0.0211j -0.6664+0.j      0.5777-0.4799j]
 [ 0.    +0.j     -0.7132+0.4798j  0.5777+0.4799j  0.1455+0.j    ]]


In [93]:
print(xij_again.round(4))


[[-0.9793+0.j      0.    -0.j      0.4202+0.3927j  0.    +0.j    ]
 [ 0.    +0.j     -0.5629+0.j      0.236 -0.0211j -0.7132-0.4798j]
 [ 0.4202-0.3927j  0.236 +0.0211j -0.6664+0.j     -0.5777+0.4799j]
 [ 0.    +0.j     -0.7132+0.4798j -0.5777-0.4799j  0.1455+0.j    ]]


In [67]:
G.shape

(4, 2, 2)

In [70]:
G[0].T

array([[0.70710678+0.j, 0.        +0.j],
       [0.        +0.j, 0.70710678+0.j]])

In [105]:
G_ijkl = np.array([[np.kron(G[j].T, G[i]) for j in range(4)] for i in range(4)])

In [113]:
np.array([[str(i)+str(j) for j in range(4)] for i in range(4)])

array([['00', '01', '02', '03'],
       ['10', '11', '12', '13'],
       ['20', '21', '22', '23'],
       ['30', '31', '32', '33']], dtype='<U2')

In [80]:
xij_example

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[-0.97925169+0.j          0.        +0.j         -0.42016706-0.39268663j
   0.        +0.j        ]
 [ 0.        +0.j         -0.56288265+0.j         -0.23599318+0.02113069j
  -0.71315046-0.47984894j]
 [-0.42016706+0.39268663j -0.23599318-0.02113069j -0.66644731+0.j
   0.57766648-0.47990421j]
 [ 0.        +0.j         -0.71315046+0.47984894j  0.57766648+0.47990421j
   0.14551963+0.j        ]]

In [81]:
G_ijkl.shape

(4, 4, 4, 4)

In [110]:
np.einsum("ij,ijkl -> kl ",  xij_example.full(), G_ijkl).round(3)

array([[-0.417+0.j   , -0.4  -0.319j, -0.4  +0.319j, -0.636+0.j   ],
       [-0.313-0.161j, -0.562+0.j   ,  0.052-0.236j,  0.793-0.739j],
       [-0.313+0.161j,  0.052+0.236j, -0.562+0.j   ,  0.793+0.739j],
       [-0.594+0.j   , -0.08 +0.259j, -0.08 -0.259j, -0.417+0.j   ]])

In [115]:
np.einsum("ij,ijkl -> kl ",  xij_example.full(), G_ijkl).round(3)


array([[-0.417+0.j   , -0.4  -0.319j, -0.4  +0.319j, -0.636+0.j   ],
       [-0.313-0.161j, -0.562+0.j   ,  0.052-0.236j,  0.793-0.739j],
       [-0.313+0.161j,  0.052+0.236j, -0.562+0.j   ,  0.793+0.739j],
       [-0.594+0.j   , -0.08 +0.259j, -0.08 -0.259j, -0.417+0.j   ]])

In [152]:
kraus_ops = np.array(qu.to_kraus(qu.rand_super_bcsz(N=2, seed=3)))

In [153]:
kraus_ops.shape

(4, 2, 2)

In [160]:
np.sum([np.conjugate(kraus_ops[i]).T@kraus_ops[i] for i in range(4)], axis=0)

array([[1.00000000e+00+0.00000000e+00j, 4.75314232e-16-1.83880688e-16j],
       [4.75314232e-16+1.83880688e-16j, 1.00000000e+00+0.00000000e+00j]])

In [ ]:
for i in range(4):
    kraus_ops[i,1]@kra

In [180]:
ket_i = np.array([qu.basis(2, i).full() for i in range(2)])
bra_i = np.array([np.conjugate(qu.basis(2, i).full()).T for i in range(2)])

In [148]:
ket_i.shape

(2, 2, 1)

In [149]:
bra_i.shape

(2, 1, 2)

In [210]:
ket_i[0]@bra_i[0]

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]])

In [209]:
bra_i[1]@ket_i[1]

array([[1.+0.j]])

In [226]:
kraus_ops.shape

(4, 2, 2)

array([[0.49131627+0.j        , 0.062577  +0.03322075j],
       [0.062577  -0.03322075j, 0.50868373+0.j        ]])

In [252]:
np.kron(ket_i[n]@bra_i[m], re)

array([[0.49131627+0.j        , 0.062577  +0.03322075j,
        0.        +0.j        , 0.        +0.j        ],
       [0.062577  -0.03322075j, 0.50868373+0.j        ,
        0.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.        +0.j        ,
        0.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.        +0.j        ,
        0.        +0.j        , 0.        +0.j        ]])

In [248]:
re = 0
n = 0
m = 0
for j in range(4):
    re = re + kraus_ops[j] @ ket_i[n] @ bra_i[m] @ np.conjugate(kraus_ops[j]).T
np.kron(ket_i[n] @ bra_i[m], re).round(3)

array([[0.491+0.j   , 0.063+0.033j, 0.063-0.033j, 0.509+0.j   ],
       [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ]])

In [265]:
def to_choi_from_kraus(kraus_ops):
    choi = 0
    for n in range(2):
        for m in range(2):
            right_side = 0
            for j in range(4):
                right_side = right_side + (
                    kraus_ops[j] @ ket_i[n] @ bra_i[m] @ np.conjugate(kraus_ops[j]).T
                )
            choi = choi + np.kron(ket_i[n] @ bra_i[m], right_side)
    return choi

In [262]:
# choi = np.zeros([2, 2, 2, 2], dtype=np.complex64)
choi = 0

for n in range(2):
    for m in range(2):
        right_side = 0
        for j in range(4):
            right_side = right_side + (
                kraus_ops[j] @ ket_i[n] @ bra_i[m] @ np.conjugate(kraus_ops[j]).T
            )
        choi = choi + np.kron(ket_i[n] @ bra_i[m], right_side)

In [263]:
choi.round(3)

array([[ 0.491+0.j   ,  0.063+0.033j, -0.26 +0.19j , -0.183-0.023j],
       [ 0.063-0.033j,  0.509+0.j   , -0.191+0.197j,  0.26 -0.19j ],
       [-0.26 -0.19j , -0.191-0.197j,  0.511+0.j   , -0.154-0.034j],
       [-0.183+0.023j,  0.26 +0.19j , -0.154+0.034j,  0.489+0.j   ]])

In [267]:
to_choi_from_kraus(kraus_ops).round(3)

array([[ 0.491+0.j   ,  0.063+0.033j, -0.26 +0.19j , -0.183-0.023j],
       [ 0.063-0.033j,  0.509+0.j   , -0.191+0.197j,  0.26 -0.19j ],
       [-0.26 -0.19j , -0.191-0.197j,  0.511+0.j   , -0.154-0.034j],
       [-0.183+0.023j,  0.26 +0.19j , -0.154+0.034j,  0.489+0.j   ]])

In [222]:
ket_i[n]@bra_i[m]

array([[0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

In [264]:
np.linalg.eig(qu.to_choi(qu.rand_super_bcsz(N=2, seed=3)))[0]

array([1.05691617-1.02703910e-16j, 0.73906774-3.31292226e-17j,
       0.03335933+2.69664647e-17j, 0.17065676+1.44665399e-17j])

In [282]:
qu.to_choi(qu.rand_super_bcsz(N=2, seed=3))

Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = (4, 4), type = super, isherm = True, superrep = choi
Qobj data =
[[ 0.49131627+2.00916215e-17j  0.062577  +3.32207463e-02j
  -0.25996387+1.89542631e-01j -0.18322722-2.32866675e-02j]
 [ 0.062577  -3.32207463e-02j  0.50868373-1.89311864e-17j
  -0.19104131+1.97431162e-01j  0.25996387-1.89542631e-01j]
 [-0.25996387-1.89542631e-01j -0.19104131-1.97431162e-01j
   0.51081089+7.26398515e-17j -0.15416612-3.43538567e-02j]
 [-0.18322722+2.32866675e-02j  0.25996387+1.89542631e-01j
  -0.15416612+3.43538567e-02j  0.48918911+3.09692186e-17j]]

In [322]:
def to_chi_from_kraus(kraus_ops):
    chi = np.zeros([4, 4], dtype=np.complex64)
    for i in range(4):
        for j in range(4):
            suma = 0 
            for m in range(4):
                suma = suma +np.trace(G[i]@kraus_ops[m])*np.trace(G[j]@np.conjugate(kraus_ops[m].T))
            chi[i, j] = suma
    return chi

## CORRECT ONE

In [323]:
to_chi_from_kraus(kraus_ops).round(3)

array([[ 0.307+0.j   , -0.046+0.223j,  0.001+0.368j,  0.001+0.023j],
       [-0.046-0.223j,  0.319+0.j   ,  0.197-0.001j, -0.152+0.001j],
       [ 0.001-0.368j,  0.197+0.001j,  0.701+0.j   ,  0.156+0.046j],
       [ 0.001-0.023j, -0.152-0.001j,  0.156-0.046j,  0.673+0.j   ]],
      dtype=complex64)

In [324]:

(to_chi_from_choi(to_choi_from_super(to_super_from_chi(to_chi_from_kraus(kraus_ops))))*2).round(3)

array([[ 0.307+0.j   , -0.046+0.223j,  0.001+0.368j,  0.001+0.023j],
       [-0.046-0.223j,  0.319+0.j   ,  0.197-0.001j, -0.152+0.001j],
       [ 0.001-0.368j,  0.197+0.001j,  0.701+0.j   ,  0.156+0.046j],
       [ 0.001-0.023j, -0.152-0.001j,  0.156-0.046j,  0.673+0.j   ]],
      dtype=complex64)

## WRONG is to choi_from_kraus

In [326]:
(to_chi_from_choi(to_choi_from_kraus(kraus_ops))*2).round(3)

array([[ 0.307+0.j   , -0.046+0.223j,  0.001+0.368j,  0.001+0.023j],
       [-0.046-0.223j,  0.319+0.j   ,  0.197-0.001j, -0.152+0.001j],
       [ 0.001-0.368j,  0.197+0.001j,  0.701+0.j   ,  0.156+0.046j],
       [ 0.001-0.023j, -0.152-0.001j,  0.156-0.046j,  0.673+0.j   ]],
      dtype=complex64)

In [327]:
to_choi_from_kraus(kraus_ops).round(3)

array([[ 0.491+0.j   ,  0.063+0.033j, -0.26 +0.19j , -0.183-0.023j],
       [ 0.063-0.033j,  0.509+0.j   , -0.191+0.197j,  0.26 -0.19j ],
       [-0.26 -0.19j , -0.191-0.197j,  0.511+0.j   , -0.154-0.034j],
       [-0.183+0.023j,  0.26 +0.19j , -0.154+0.034j,  0.489+0.j   ]])

In [286]:
qu.to_choi(qu.rand_super_bcsz(N=2, seed=3))

Quantum object: dims = [[[2], [2]], [[2], [2]]], shape = (4, 4), type = super, isherm = True, superrep = choi
Qobj data =
[[ 0.49131627+2.00916215e-17j  0.062577  +3.32207463e-02j
  -0.25996387+1.89542631e-01j -0.18322722-2.32866675e-02j]
 [ 0.062577  -3.32207463e-02j  0.50868373-1.89311864e-17j
  -0.19104131+1.97431162e-01j  0.25996387-1.89542631e-01j]
 [-0.25996387-1.89542631e-01j -0.19104131-1.97431162e-01j
   0.51081089+7.26398515e-17j -0.15416612-3.43538567e-02j]
 [-0.18322722+2.32866675e-02j  0.25996387+1.89542631e-01j
  -0.15416612+3.43538567e-02j  0.48918911+3.09692186e-17j]]

In [271]:
to_super_from_chi(to_chi_from_kraus(kraus_ops))

array([[ 0.00781654+0.j        ,  0.01958156-0.00079138j,
         0.01958156+0.00079138j,  0.04913473+0.j        ],
       [ 0.00506976-0.02508465j, -0.00517604+0.01438925j,
         0.01524014-0.06232736j, -0.01442353+0.03552308j],
       [ 0.00506976+0.02508465j,  0.01524014+0.06232736j,
        -0.00517604-0.01438925j, -0.01442353-0.03552308j],
       [ 0.08378923+0.j        , -0.04953474-0.00727803j,
        -0.04953474+0.00727803j,  0.02991626+0.j        ]])