# Comparing using choi matrix vs letting both dots evolve under same map

In [1]:
import numpy as np
import jax
import jax.numpy as jnp
from jax import vmap, jit
import matplotlib.pyplot as plt
import joblib
from qdots_qll.models import game
from qdots_qll import all_funcs
import seaborn as sns
import pandas as pd
import scipy

In [2]:
# I need to include the results which come from not using choi:

not_choi_results = joblib.load(
    "../results/run_2024-01-11_16:51:55_results.job"
)
not_choi_model = joblib.load("../results/run_2024-01-11_16:51:55_model.job")

# and the ones using choi:

choi_results = joblib.load("../results/run_2024-01-02_18:33:28_results.job")
choi_model = joblib.load("../results/run_2024-01-02_18:33:28_model.job")

In [3]:
true_parameters = game.true_pars

In [6]:
final_estimates_not_choi = jax.vmap((lambda a, b: a[b]), in_axes=(0, 0))(
    not_choi_results.estimates_array, not_choi_results.iteration
)

final_estimates_choi = jax.vmap((lambda a, b: a[b]), in_axes=(0, 0))(
    choi_results.estimates_array, choi_results.iteration
)

In [7]:
final_estimates_choi

Array([[ 0.30041716,  0.35603192,  0.09580585, -0.29877377],
       [ 0.3512567 ,  0.33713788,  0.09160274, -0.25727472],
       [ 0.32094073,  0.35002723,  0.0728352 , -0.27165988],
       ...,
       [ 0.35171276,  0.35749123,  0.06053098, -0.2775493 ],
       [ 0.31512463,  0.36265057,  0.0364621 , -0.329189  ],
       [ 0.3792564 ,  0.4015895 ,  0.08362823, -0.28777388]],      dtype=float32)

In [5]:
final_estimates_not_choi

Array([[ 0.29650414,  0.3534567 ,  0.10339864, -0.28793088],
       [ 0.3435552 ,  0.42819053,  0.09127641, -0.26399252],
       [ 0.3209407 ,  0.3500274 ,  0.07283518, -0.2716599 ],
       ...,
       [ 0.32668954,  0.39183483,  0.04070732, -0.3920905 ],
       [ 0.31512466,  0.3626506 ,  0.03646209, -0.32918903],
       [ 0.37925655,  0.40158954,  0.08362815, -0.28777415]],      dtype=float32)

In [8]:
def mean_std(arr):
    return np.array(arr.mean(axis=0)), np.array(arr).std(axis=0)

In [9]:
mean_std(final_estimates_choi)

(array([ 0.32137072,  0.36798579,  0.05970253, -0.32731265], dtype=float32),
 array([0.03366981, 0.03789891, 0.03057473, 0.0495873 ], dtype=float32))

In [10]:
mean_std(final_estimates_not_choi)

(array([ 0.32673478,  0.37356776,  0.06481925, -0.31690994], dtype=float32),
 array([0.0353648 , 0.03718231, 0.03684504, 0.05846002], dtype=float32))

In [11]:
from scipy.stats import ttest_ind

In [24]:
results_t_test = ttest_ind(
    final_estimates_choi, final_estimates_not_choi, axis=0, equal_var=False
)

In [25]:
results_t_test.pvalue

array([0.01430591, 0.01904427, 0.01716643, 0.00249929], dtype=float32)

with $\alpha=0.05$, we can reject the null hypothesis H0 and say the  means are different.